
@host = https://f4d5341f-8f43-4a42-b9e7-fd8a0c1cfb37-00-5ni5latmswlf.janeway.replit.dev
@host = http://localhost:4000
@host = https://pasteleriagraphql-production.up.railway.app
###
curl --request POST \
  --header 'content-type: application/json' \
  --url {{host}}/graphql \
  --data '{"query":"query { health }"}'


###
curl --request POST \
  --header 'content-type: application/json' \
  --url {{host}}/graphql \
  --data '{"query":"query { productsByIngredients(ingredientNames: [\"chocolate\"]) { id name } }"}'

###
curl --request POST \
  --header 'content-type: application/json' \
  --url {{host}}/graphql \
  --data '{"query":"query { cakesByIngredients(ingredientNames: [\"chocolate\"]) { id name } }"}'

###
curl --request POST \
  --header 'content-type: application/json' \
  --url {{host}}/graphql \
  --data '{"query":"query { dessertsByIngredients(ingredientNames: [\"chocolate\"]) { id name } }"}'

###
curl http://192.168.0.2:8080/api/v1.0/products/desserts?ingredients=manjar