
@host = https://f4d5341f-8f43-4a42-b9e7-fd8a0c1cfb37-00-5ni5latmswlf.janeway.replit.dev

@host = pasteleriagraphql-production.up.railway.app

@host = http://localhost:4000

###
curl --request POST \
  --header 'content-type: application/json' \
  --url {{host}}/graphql \
  --data '{"query":"query { health }"}'


###
curl --request POST \
  --header 'content-type: application/json' \
  --url {{host}}/graphql \
  --data '{"query":"query { productsByIngredients(ingredientName: [\"chocolate\"]) { id name } }"}'